In [1]:
import caffe

In [2]:
import h5py
import numpy as np

In [3]:
net = caffe.Net('/home/menglin/caffe-master/menglin_try/cardata_resnet.prototxt', '/home/menglin/caffe-master/menglin_try/snapshot_iter_100000.caffemodel', caffe.TEST)

In [4]:
net.blobs['conv1'].diff.shape

(64, 32, 33, 33)

In [8]:
net.blobs['ip2'].diff.shape

(64, 5)

In [6]:
net.blobs['loss'].diff.shape

()

In [5]:
dat = net.params['conv1'][0].data

In [6]:
dat.shape

(32, 3, 31, 31)

In [8]:
dat.size

92256

In [9]:
dat.shape

(32, 3, 31, 31)

In [10]:
res2_conv2.shape

(32, 32, 7, 7)

In [11]:
res2_conv2[0,0:31,0:6,0:6]

array([[[  4.88676167e+00,   2.23719031e-01,   2.68359810e-01,
           4.77111898e-02,   4.17852908e-01,   1.09128013e-01],
        [  4.32940751e-01,  -5.46624959e-01,  -1.19167697e+00,
           6.51976585e-01,   3.34077984e-01,   3.90929818e-01],
        [  3.31940114e-01,   1.28987873e+00,   2.23326564e-01,
           8.32145035e-01,  -1.69923401e+00,  -1.33538091e+00],
        [ -3.07671690e+00,  -1.61234701e+00,  -4.61142898e-01,
           2.21717238e+00,   3.67922634e-02,  -1.11026943e+00],
        [ -1.71315825e+00,  -2.74625134e+00,  -1.74684057e-04,
           4.03643894e+00,   3.54194236e+00,   2.46464372e+00],
        [ -2.26468039e+00,  -2.69245887e+00,  -3.92316413e+00,
           6.63718954e-02,   2.12171412e+00,  -3.25832926e-02]],

       [[  6.71325386e-01,   2.69248098e-01,   2.41849589e+00,
           1.57536960e+00,   1.15687954e+00,  -9.68955636e-01],
        [ -1.46594560e+00,  -1.58384013e+00,  -1.45804954e+00,
          -6.00434303e-01,   9.23765957e-01,  

In [12]:
ip2 =  net.params['ip2'][0].data

In [15]:
ip2.shape

(5, 1000)

In [16]:
ip2[0,0:999]

array([ 89.04793549, -98.87715912,  88.95400238,  88.98031616,
        89.03479767,  88.97054291, -98.90836334,  88.95876312,
       -98.90298462,  88.97679138, -98.93023682,  88.92116547,
        89.02069855,  89.02079773,  89.04850769,  88.97132111,
       -98.86769104,  88.95516968, -98.81963348, -98.95080566,
        88.9309845 ,  88.96354675,  88.7026825 ,  88.97626495,
       -98.91255188, -98.93808746,  88.98113251,  89.03302765,
        88.97312164, -98.88677979,  88.95477295,  89.03043365,
        88.91217804,  88.89716339, -98.92156219, -98.93645477,
       -98.89211273, -98.87673187,  88.90133667,  88.967659  ,
       -98.96025848, -98.95967865, -98.84285736,  88.91653442,
        89.00569916,  88.99018097,  88.96327209,  89.02431488,
        88.98877716, -98.89915466,  88.92626953,  89.0070343 ,
        88.88206482,  88.91411591,  88.98229218,  88.98129272,
        88.95546722, -98.9410553 , -98.92473602,  88.9848175 ,
       -98.96092224, -98.94774628,  88.98014832, -98.94

In [18]:
ip2[1,0:999]

array([ 83.51540375, -98.65509796,  83.63652039,  83.62562561,
        83.61467743,  83.39365387, -99.02820587,  83.52833557,
       -98.67530823,  83.61740875, -98.93510437,  83.54982758,
        83.4862442 ,  83.65132141,  83.69566345,  83.44422913,
       -98.91919708,  83.63751221, -98.94319153, -98.92591095,
        83.42115784,  83.63967133,  82.4813385 ,  83.4590683 ,
       -98.97555542, -99.02082062,  83.52677917,  83.60643005,
        83.65879822, -98.90966034,  83.50170135,  83.54071045,
        83.50617218,  83.43569183, -98.88407135, -99.01169586,
       -99.02510834, -98.92934418,  83.45081329,  83.48958588,
       -99.01093292, -99.00410461, -98.76721191,  83.58978271,
        83.62503052,  83.53885651,  83.56328583,  83.5418396 ,
        83.47307587, -98.65885162,  83.59242249,  83.58886719,
        83.49388123,  83.39546967,  83.58343506,  83.4679184 ,
        83.61623383, -99.00728607, -98.8275528 ,  83.63307953,
       -99.03768921, -98.85184479,  83.57277679, -98.98

In [20]:
ip1 =  net.params['ip1'][0].data

In [21]:
ip1.shape

(1000, 2048)

In [22]:
ip1[0,0:2047]

array([-0.0108929 , -0.62493843,  0.01433866, ...,  0.34388825,
       -0.07750359,  0.17455676], dtype=float32)

In [24]:
ip4 =  net.params['ip4'][0].data

In [25]:
ip4.shape

(4, 1000)

In [26]:
ip4[0,0:999]

array([ -2.36708567e-01,  -8.15788984e-01,   7.65449464e-01,
        -3.69013399e-01,  -6.32777214e-01,  -4.48543608e-01,
         5.48508227e-01,  -1.19566047e+00,   3.86130691e-01,
        -6.50669122e-03,   1.61266005e+00,   3.30778748e-01,
         1.12320080e-01,   7.86533356e-01,   7.08495200e-01,
         6.52059913e-03,   1.70042261e-01,  -9.80155587e-01,
         4.45944756e-01,   4.89461452e-01,   2.81829000e-01,
        -2.66550225e-03,   1.58759689e+00,   2.48200268e-01,
        -4.20946106e-02,   5.55512130e-01,   7.57393688e-02,
         6.06742859e-01,  -3.74092549e-01,  -6.98046982e-01,
         2.43341833e-01,   1.45389527e-01,   2.10669070e-01,
         2.59450963e-03,  -2.67222136e-01,  -6.54872537e-01,
         4.37221467e-01,   2.89659619e-01,   1.54947484e+00,
         3.27329874e-01,  -7.04266250e-01,   4.74972486e-01,
         1.92727402e-01,   5.15267372e-01,  -6.80379093e-01,
         4.51378934e-02,  -1.01925910e+00,  -9.02680933e-01,
         2.48611510e-01,

In [27]:
ip4 =  net.params['ip4'][1].data

In [28]:
ip4.shape


(4,)

In [29]:
ip4

array([ 1.9088608 ,  1.84578311,  8.49126053,  6.29635   ], dtype=float32)

In [32]:
ip2 =  net.params['ip2'][0].data

In [33]:
ip2

array([[ 89.04793549, -98.87715912,  88.95400238, ...,  88.99343109,
         88.92707062,  88.99993134],
       [ 83.51540375, -98.65509796,  83.63652039, ...,  83.64649963,
         83.53749847,  83.6264267 ],
       [ 80.28736115, -98.52542877,  80.39444733, ...,  80.43041992,
         80.3627243 ,  80.42832184],
       [ 87.96944427, -98.96286774,  87.84529114, ...,  87.85955048,
         87.93241882,  87.846138  ],
       [ 89.03168488, -98.9524765 ,  88.9150238 , ...,  88.95934296,
         88.92491913,  88.91458893]], dtype=float32)